from tkinter import *
import tkinter.messagebox as messagebox
from tkcalendar import DateEntry
from tkinter import ttk
from PIL import Image,ImageTk
from csv import writer
a=Tk()
a.title('Hospital Data Analysis')
a.iconbitmap('Data_stuff.ico')
width=600
height=525
screenwidth = a.winfo_screenwidth()
screenheight = a.winfo_screenheight()
alignstr = '%dx%d+%d+%d' % (width, height, (screenwidth - width) / 2, (screenheight - height) / 2)
a.geometry(alignstr)
'''mainframe=Frame(a)
mainframe.pack(fill=BOTH,expand=1)
mycan=Canvas(mainframe)
mycan.pack(side=LEFT,fill=BOTH,expand=1)
scroll=ttk.Scrollbar(mainframe,orient=VERTICAL,command=mycan.yview)
scroll.pack(side=RIGHT,fill=Y)
mycan.configure(yscrollcommand=scroll.set)
mycan.bind('<Configure>',lambda e: mycan.configure(scrollregion=mycan.bbox('all')))
secondframe=Frame(mycan)
mycan.create_window((0,0),window=secondframe, anchor='nw')'''
img=ImageTk.PhotoImage(Image.open('poster.jpg'))
label=Label(a,image=img,bg='purple')
label.pack()
s = ttk.Style()
s.theme_use('default')
s.configure('TNotebook.Tab', background="orange3")
s.map("TNotebook", background= [("selected", "orange3")])
tabcontrol=ttk.Notebook(a)
tab1 = Frame(tabcontrol, background="yellow") 
tab2 = Frame(tabcontrol, background="yellow") 
tab3 = Frame(tabcontrol, background="yellow")
tabcontrol.add(tab1,text='Data Entry')
tabcontrol.add(tab2,text='Data Analysis')
tabcontrol.add(tab3,text='Notes')
tabcontrol.pack(expand=1,fill='both')
l=[]
def printInput():
    inp = inputtxt.get(1.0, "end-1c")
    lbl.config(text = "Provided Input: "+inp)
def importcsv():
    x=var.get()
    if x=='':
        messagebox.showwarning('Warning','Empty Box')
    else:
        messagebox.showinfo('Success')
        k=[var.get(),var1.get(),var2.get(),var3.get(),var4.get(),var5.get(),inp,inp1,inp2,inp3,inp4,inp5,inp6]
        for i in range(7):
            if k[i+6]=='':
                k[i+6]=0
            else:
                k[i+6]=int(k[i+6])
        l.append(k)
        with open('CSVFILE.csv', 'a', newline='') as f_object:
            writer_object = writer(f_object)
            writer_object.writerow(k)
            f_object.close()
    x=pd.read_csv('CSVFILE.csv')
    print(x)
lbl=Label(tab1,text='Hospital Name', bg='blue', fg='white')
lbl.place(x=10,y=10)
var=StringVar()
ent= Entry(tab1,bg='light blue',bd=4,textvariable=var)
ent.place(x=100,y=10)
lbl=Label(tab1,text='City')
lbl.place(x=10,y=40)
var1=StringVar()
ent= Entry(tab1,textvariable=var1)
ent.place(x=10,y=60)
lbl=Label(tab1,text='District')
lbl.place(x=100,y=40)
var2=StringVar()
ent= Entry(tab1,textvariable=var2)
ent.place(x=100,y=60)
lbl=Label(tab1,text='State')
lbl.place(x=200,y=40)
var3=StringVar()
ent= Entry(tab1,textvariable=var3)
ent.place(x=200,y=60)
lbl=Label(tab1,text='Country')
lbl.place(x=300,y=40)
var4=StringVar()
ent= Entry(tab1,textvariable=var4)
ent.place(x=300,y=60)

lbl=Label(tab1,text='Date', bg='orange', fg='white')
lbl.place(x=10,y=90)
var5=StringVar()
cal=DateEntry(tab1,selectmode='day',bg='yellow',textvariable=var5)
cal.place(x=50,y=90)

lbl=Label(tab1,text='Patients')
lbl.place(x=10,y=120)
inp=StringVar()
ent= Entry(tab1,textvariable=inp)
ent.place(x=10,y=140)
lbl=Label(tab1,text='Beds')
lbl.place(x=100,y=120)
inp1=StringVar()
ent= Entry(tab1,textvariable=inp1)
ent.place(x=100,y=140)
lbl=Label(tab1,text='Deaths')
lbl.place(x=200,y=120)
inp2=StringVar()
ent= Entry(tab1,textvariable=inp2)
ent.place(x=200,y=140)
lbl=Label(tab1,text='Cancer')
lbl.place(x=300,y=120)
inp3=StringVar()
ent= Entry(tab1,textvariable=inp3)
ent.place(x=300,y=140)
lbl=Label(tab1,text='Tuberculosis')
lbl.place(x=400,y=120)
inp4=StringVar()
ent= Entry(tab1,textvariable=inp4)
ent.place(x=400,y=140)
lbl=Label(tab1,text='accidents')
lbl.place(x=500,y=120)
inp5=StringVar()
ent= Entry(tab1,textvariable=inp5)
ent.place(x=500,y=140)
lbl=Label(tab1,text='pneumonia')
lbl.place(x=600,y=120)
inp6=StringVar()
ent= Entry(tab1,textvariable=inp6)
ent.place(x=600,y=140)
btn=Button(tab1,bg='brown',text='Submit',command=importcsv)
btn.place(x=20,y=200)
inputtxt = Text(tab3,
                   height = 5,
                   width = 20)
inputtxt.pack()
printButton = Button(tab3,
                        text = "Print", 
                        command = printInput)
printButton.pack()
lbl = Label(tab3, text = "")
lbl.pack()
a.configure(bg='sky blue')
a.mainloop()